[package]
name = "tide-websockets"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
async-tungstenite = "0.10.0"
sha-1 = "0.9.2"
base64 = "0.13.0"
env_logger = "0.8.2"
tide = "0.15.0"
futures-util = "0.3.8"
async-std = { version = "1.7.0", features = ["attributes"] }
pin-project = "1.0.2"
async-dup = "1.2.2"
serde_json = "1.0.59"
serde = "1.0.117"

[patch.crates-io.http-types]
git = "https://github.com/http-rs/http-types"
branch = "stabilize-upgrade"

[patch.crates-io.async-h1]
git = "https://github.com/jbr/async-h1"
branch = "upgrades"
